- src/camera-controls.js
current method we're doing interpolation at `update()` can do weird behavior under extreme situation (laggy environment like 10FPS, or higher damping factor such as `0.5` or `1.0` or w/e).
We should use `Math.exp` instead here, so it guarantees `target` / `spherical` to be converged to desired location (even if damping factor is `Infinity` )!
It has minor compatibility break (does different behavior under high damping factor) but I recommend to apply this change.
> We should use Math.exp instead

- examples/basic.html
- readme.md
- src/camera-controls.js
- `setLookAt( position, target, enableTransition )`
It moves the camera into `position` , and also make it look at `target` .
- `lerpLookAt( positionA, targetA, positionB, targetB, x, enableTransition )`
Same as `setLookAt` , but it interpolates between two states.
- `setPosition( position, enableTransition )`
`setLookAt` without `target` , Stay gazing the current target.
- `setTarget( target, enableTransition )`
`setLookAt` without `position` , Stay still at the position.
- `getPosition()`
Return its current position.
- `getTarget()`
Return its current gazing target.
- I added the private function `_sanitizeSphericals()` .
It clamps `_sphericalEnd.theta` into `0` ~ `TAU` and also make `_spherical` in range between `_sphericalEnd.theta - PI` ~ `_sphericalEnd.theta` + PI,
It prevents …
> Implemented `setLookAt` and `lerpLookAt`

- examples/basic.html
- readme.md
- src/camera-controls.js
Currently other API does not depend on THREE's root itself but `setLookAt` and `lerpLookAt` does.
It's no cool! (yes it's definitely my fault, sorry 😖 )
So I made it possible to receive JavaScript `Array` instead of `THREE.Vector3`.
> `setLookAt` / `lerpLookAt` now receives number literals instead of `THREE.Vector3`

- readme.md
- src/camera-controls.js
- src/event-dispatcher.js
See #18.
`CameraControls` now inherits [`EventDispatcher`](https://github.com/FMS-Cat/camera-controls/blob/537d6f5a3703efe8f7d128ea7e0156fa79b79f64/src/event-dispatcher.js)
(The source is completely same as https://github.com/mrdoob/three.js/blob/master/src/core/EventDispatcher.js)
We initially have these events:
- `controlstart`
when `mousedown` or `touchstart` is occured
- `control`
when `mousemove` or `touchmove` is occured
- `controlend`
when `mouseup` or `touchend` is occured
- `update`
When the camera is updated via controls or transition
> Implement event dispatcher

- src/camera-controls.js
一度にいろいろやっちゃってすいません。
---
Currently we are dealing with wheel events (to perform dolly) without support of `event.wheelDelta` / `event.deltaY` ([this is completely same implementation as original OrbitControls](https://github.com/mrdoob/three.js/blob/master/examples/js/controls/OrbitControls.js#L524-L532)) .
This is making a mess under specific environments that wheel controls are ultrasmooth (e.g. single tick of wheel movement sustains for 50 or more frames).
Here is the reference of wheel control implementation in osgjs (Sketchfab engine), which uses `event.wheelDelta` / `event.deltaY` to achieve cross platform support (hardwares / OSes / browsers).
https://github.com/cedricpinson/osgjs/blob/00e5a7e9d9206c06fdde0436e1d62ab7cb5ce853/sources/osgViewer/input/source/InputSourceMouse.js#L89-L10 …
> Update controls (wheel, touchEvents and dampingFactor)

- src/camera-controls.js
Previously, translation of `_target` occurs in `dollyToCursor` procedure via mouse wheel events could be happened more than once within a frame, especially under low frame rate conditions.
This PR will fix this problem, since `_target` translation operation is now in `update()` !
> DollyToCursor:  It's now not raycaster/object dependant

- src/camera-controls.js
Users may set `boundaries` at out of 'target'. then `target` will eventually locates out of bounding-box.
For example, user may set the `boundaries` as `( -100, -100, -100 ), ( -90, -90, -90 )`
This PR is to reduce the probrem.
> boundary must have the setter

- examples/basic.html
- readme.md
- src/camera-controls.js
- types/camera-controls.d.ts
An attempt to resolve #34
- New property: `.boundary`
- Is a `THREE.Box3` encloses the camera target into a certain region
- New property: `.boundaryFriction`
- Friction ratio of the boundary, can tweak boundaries behavior when the camera target is in collision
- New property: `.boundaryEnclosesCamera`
- Whether camera position also should be enclosed in the boundary or not
- plus
- Update `examples/basic.html`
- Update README
> Add boundary feature

- readme.md
- src/camera-controls.js
- types/camera-controls.d.ts
Add viewport support for the CameraControls.
When you set viewport to your renderer, the `dollyToCursor` option does not work properly,
since it uses canvas' `getBoundingClientRect` .
The PR adds a new `.setViewport()` method to `CameraControls` .
The viewport is not required but if you set this
you can make the `dollyToCursor` works properly even if renderer's viewport is set.
> Add viewport support

- src/camera-controls.js
When you attempt to pan or truck the camera using touch screen,
it causes unintended behavior under certain conditions: when the document is scrolled.
This PR fixes the issue.
> Fix touch pan/truck issue

- src/camera-controls.js
This PR adds the functionality for any camera.up vector. It follows the implementation of `OrbitControls` from the official repository of threejs.
There is also a minor modification suggested for the case when dollyToCursor is enabled and the view direction is exactly equal to the camera.up vector, for which dollyToCursor does not function.
All the examples in the repository have been tested with `camera.up = (0, 0, 1)` which is the main alternative to the default settings and everything works as expected.
Not being a Javascript experienced user it is possible that the implemented code could be improved, although pretty straightforward. I leave that to the discretion of the reviewers.
> Implement functionality for any camera.up vector

- examples/camera-up.html
- readme.md
- src/camera-controls.js
Implementing the module in my project where I use `camera.up = (0, 0, 1)` I realized that the positioning of the camera in the `setLookAt` method was not modified accordingly to all the `sphericalEnd.setFromVector3` calls in the PR that implemented the utility of the camera controls for any camera.up vector, resulting, thus, in an erroneous position placement of the camera.
This behavior can be reproduced by eliminating line 57 from the `camera-up.html` example
```
camera.position.set( 0, 5, 0 );
```
and by adding the following at line 62 just after the definition of cameraControls
```
cameraControls.setLookAt( 0, 5, 0, 0, 0, 0, true );
```
This PR fixes this bug and updated the example to test the correct behavior.
> fix setLookAt from any camera.up

- src/CameraControls.ts
This is a PR to allow camera trucking for non-pinch trackpad gestures. I left comments but this relies on two tricks... the first is detection of a trackpad based on wheelDeltaX/Y (which typescript doesn't seem to like) here: https://stackoverflow.com/questions/10744645/detect-touchpad-vs-mouse-in-javascript/56948026#56948026
This may be only for Mac trackpads... please modify if there is something better...
The second trick is detecting pinch vs. non-pinch via `ctrlKey` as shown here: https://stackoverflow.com/questions/15416851/catching-mac-trackpad-zoom/28685082#28685082...
Also I would prefer to have this as an option but I didn't want to guess as to how you would like the API so I leave that to you.. maybe something as simple as `cameraControls.trackpad.emulateTruck`? I'm not sure. …
> Allow trackpad to truck on non-pinch gesture.

- package.json
`three` should be in peerDependencies I think because:
- camera-controls has no use without three.js
- its type definitions depends on three
> three should be in peerDependencies

- src/CameraControls.ts
Hi,
I was trying to remove the listener on the wheel, because sometimes the canvas is just a part of the page. While it works well when ACTION.NONE is specified, it just blocks the scroll when you are on top of the canvas (because of the e.preventDefault). So before entering the function, we can just check if controls are enabled and if the user config is not NONE.
I'm not very familiar with TypeScript, I hope this change is acceptable.
Thank for your job by the way !
> Update onMouseWheel listener

- src/CameraControls.ts
This is critical when using an orthographic camera.
Closes #87
> Add zoom state to toJSON() and fromJSON()

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/93
> exposing angles

- readme.md
I ran into problems the first time I used camera-controls, because I didn't copy the example usage code, which contains the line `CameraControls.install( { THREE: THREE } )`. This is neccesary for camera-controls to work, but is not explicitly stated. I've added a warning to remind the user about the importance of running that line.
> Updated readme.md to prompt the user to run CameraControls.install()

- readme.md
- src/CameraControls.ts
I thought Dolly can be used for z-offset but may conflict with `minDistance` and `maxDistance`.
So, `setFocalOffset()` should take z-offset.
Altho it does not affect in Orthographic...
(For a workaround for Ortho see https://github.com/yomotsu/camera-controls/issues/130#issuecomment-697007648 )
> focal offset should take z-offset for PerspectiveCamera

- readme.md
- src/CameraControls.ts
- Mirror other properties (target, position, etc.) by adding `getFocalOffset()`.
- Useful because sometimes `setFocalOffset()` values need to be calculated as a function of the current values, which are changed during trucking.
- Preserve focalOffset, focalOffset0 in `toJSON()`/`loadJSON()`.
- Needed for completeness for recreating camera state.
> Update get/toJSON/loadJSON methods with focalOffset

- src/CameraControls.ts
It seems doing `fitToBox` against empty boxes completely messes its internal state up since `v1.20.x`.
First of all I don't think people wants to do `fitToBox` against empty boxes.
> feat: make `fitToBox()` abort itself when it is given an empty box

- package-lock.json
- package.json
- src/CameraControls.ts
- src/types.ts
- src/utils/notSupportedInOrthographicCamera.ts
Really a very simple change to use zoom instead of dolly in fitToSphere in the case of orthographic camera.
Additionally, it includes a bit of refactoring:
* use type guards for camera type
* run eslint autofix
* run npm update (outdated eslint had a bug with type guards)
> add fitToSphere support for orthographic camera

- .github/workflows/npm.yml
Your GitHub Releases are out of sync with your npm version tag.
You could add a Github Action for publishing to npm on every Github Release,
as described in https://docs.github.com/en/actions/guides/publishing-nodejs-packages.
You just need to add your npm authentication token (`NODE_AUTH_TOKEN`) to your Github settings.
> Add Github Action for npm publishing

- src/CameraControls.ts
On mobile device i was seeing a lot of `Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted`.
This fixes it
> fix: prevent warning on mobile devices

- examples/focal-offset.html
- readme.md
- src/CameraControls.ts
We find the solution to set orbit point without changing the camera position
```ts
setOrbitPoint( targetX: number, targetY: number, targetZ : number ) {
_xColumn.setFromMatrixColumn( this._camera.matrixWorldInverse, 0 );
_yColumn.setFromMatrixColumn( this._camera.matrixWorldInverse, 1 );
_zColumn.setFromMatrixColumn( this._camera.matrixWorldInverse, 2 );
let cameraToPoint = new THREE.Vector3( targetX, targetY, targetZ ).sub( this._camera.position );
_xColumn.multiplyScalar( cameraToPoint.x );
_yColumn.multiplyScalar( cameraToPoint.y );
_zColumn.multiplyScalar( cameraToPoint.z );
_v3A.copy( _xColumn ).add( _yColumn ).add( _zColumn );
_v3A.z = _v3A.z + this.distance;
this.setFocalOffset( - _v3A.x, _v3A.y, - _v3A.z, false );
this.moveTo( targetX, targetY, targetZ, false );
}
```
> Add orbit point method fix #130

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/219
> Fix: TOUCH_DOLLY_OFFSET does not respect minDistance and maxDistance

- src/CameraControls.ts
Calling `setBoundary()` without parameters causes _`Expected 1 arguments, but got 0.ts(2554)`_ error.
This PR simply makes the parameter optional – as [described in the doc](https://github.com/yomotsu/camera-controls#setboundary-box3-).
> Set parameter to optional

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/270
`deltaZoom` is not watched in the condition for emitting `'rest'` event, then it causes #270.
This PR is to fix the problem.
> the rest event should watch deltaZoom in update()

- src/CameraControls.ts
see: https://github.com/yomotsu/camera-controls/issues/276
`fitToBox()` does not consider non Yup space. This PR is to fix the problem.
> fitToBox: adjust non Yup space

- examples/fit-and-padding.html
- readme.md
- src/CameraControls.ts
- src/types.ts
see: https://github.com/yomotsu/camera-controls/issues/286
This PR is to add `cover` option in fitToBox(), to allow users to fill the entire screen with the target box.
> cover option in fitToBox

- src/CameraControls.ts
I found that fitToBox not working properly in non-Yup space. There is closed issue #276 about the same problem but in some circumstances it is still broken. This PR should fix two issues I found, and I believe make fitToBox work properly in every scenario in non-Yup space.
1. When one dimension of box is smaller than two others - fitting to most of the box sides is broken.
2. When fit from up or bottom - box is fitted always to the same size, despite changing azimuth angle by 90 deg.
1. open https://yomotsu.github.io/camera-controls/examples/camera-up.html
3. open console
2. run:
```
const box = new THREE.Box3(
new THREE.Vector3(0, 0, 0),
new THREE.Vector3(0.1, 0.5, 0.1),
);
scene.add(new THREE.Box3Helper(box));
cameraControls.rotateTo(Math.PI * 0.5, Math.PI * 0.5, true); …
```
> fix fitToBox in non-Yup space

- src/CameraControls.ts
This PR is to fix https://github.com/yomotsu/camera-controls/issues/298
(sorry for the video quality, due to upload file size limitation)
<video src="https://user-images.githubusercontent.com/212837/186369918-9a973e19-18ea-4850-8c05-5534dbe0d1b9.mp4"></video>
> dollyToCursor should keep within boundaries

- src/CameraControls.ts
zoom-to-cursor in OrthographicCamera will no longer behave as dolly-to-cursor.
related to:
- https://github.com/yomotsu/camera-controls/issues/169
- https://github.com/yomotsu/camera-controls/issues/239
> fix: zoom-to-cursor in OrthographicCamera

- src/CameraControls.ts
This PR fixes an issue where it would zoom instead of dolly if `this._state` had other flags set.
You can observe the current behavior [in the examples](https://yomotsu.github.io/camera-controls/examples/basic.html).
If you hold down the middle mouse button and also hold down the right mouse button at the same time, then drag, the camera will start to `zoom + truck` instead of `dollying + truck`.
Fixed by checking the flag instead of doing  `===` comparison.
I think the next if statement below might also have the same issue, but I don't have touch controls to test with.
> Fix check for dolly state when dragging

- src/CameraControls.ts
Fixes https://github.com/yomotsu/camera-controls/issues/335
> Apply polar angle constraints in the setTarget method

- examples/r3f.html
- src/CameraControls.ts
Introducing a `.connect` method to allow binding events and side-effects independently from the instanciation:
```ts
const cameraControls = new CameraControls(camera)
cameraControls.connect(renderer.domElement)
cameraControls.dispose()
cameraControls.connect(renderer.domElement)
cameraControls.dispose()
```
Backward compatible:
```ts
const cameraControls = new CameraControls(camera, renderer.domElement) // auto-`connect`ed
```
This is useful in order [`<CameraControls>` drei component](https://github.com/pmndrs/drei#controls) to work properly with r3f.
See: https://github.com/yomotsu/camera-controls/issues/262#issuecomment-1399431569
> r3f `.connect` method

- src/EventDispatcher.ts
I got the following TS error, while adding a new `makeDefault` prop for the drei component in https://github.com/pmndrs/drei/pull/1247:
The `EventDispatcher.hasEventListener` was commented, I'm not sure why... I tried uncommented it and check the tests were still ok.
I let you confirm @yomotsu
> missing `EventDispatcher`.`hasEventListener` method

- examples/fit-to-bounding-sphere.html
- src/CameraControls.ts
I found that it could be useful to borrow the inner `createBoundingSphere` function.
Starting with the `examples/fit-to-bounding-sphere.html` which was needing it and has to redefined it.
=> I've just made this inner function a static method, and make `examples/fit-to-bounding-sphere.html` using it :)
Let me give you some context...
In my project, for debug purposes, I wanted to show the bounding sphere of `myMesh` (like in the `fit-to-bounding-sphere`). Primarily, I've created my own BS from `myMesh` but I figured out it was a little bigger that the one CC internally relies on to fitTo...
> Exposing `CameraControls.createBoundingSphere`

- examples/fit-to-bounding-sphere.html
`reset` button was currently broken due to `cameraControls` var is not global due to `<script type="module">`
This PR just fix this.
> fix(examples/fitToSphere): reset button

- src/CameraControls.ts
When using drei `<CameraControls enabled={false} />`, the CC instance is not immediately connected `new CameraControls(camera)`, but `.enabled = false` still happens.
https://github.com/yomotsu/camera-controls/blob/9f7b74398fe3fb7f4eba9b9de8cdcb915e8530ae/src/CameraControls.ts#L1177-L1179
was preventing the value to be set.
A minimal example with drei component, demoing the issue:
https://codesandbox.io/s/cameracontrols-basic-forked-b6qbfg?file=/src/App.js
> Do not prevent `.enabled = ` before being `.connect()`ed

- .husky/pre-commit
- .lintstagedrc.json
- package-lock.json
- package.json
Automatically lint staged files on pre-commit.
This aims at simplifying/securing the contribution process: if fixable, it will be fixed, otherwise commit won't happen and dev will have to fix manually in order to do his commit.
```sh
$ git checkout dev
$ git checkout -b husky
$ git remote add abernier https://github.com/abernier/camera-controls.git
$ git pull abernier husky
$ npm ci
```
```sh
$ echo 'console.log("no space inside parens");' >> src/utils/math-utils.ts
$ npm run lint
> camera-controls@2.2.1 lint
> eslint src --ext ts
/Users/abernier/Sites/camera-controls/src/utils/math-utils.ts
170:1   error  Expected blank line before this statement  padding-line-between-statements
170:12  error  There must be a space after this paren     space-in-parens
170:37  error  There must be a space …
```
> husky + lint-staged

- src/CameraControls.ts
- src/types.ts
see https://github.com/yomotsu/camera-controls/issues/372
if right/middle drag ends outside of window, it can't be detected by JS (AFAIK).
Check for zombie pointers that were not detected in the previous drag, on drag start, and discard them.
> dispose zombie pointer

- src/utils/math-utils.ts
reported by Ceyco on Discord.
If `maxSpeed` is set, movement may not reach to the end.
Because the end target was mutable in `smoothDamp`.
This PR is to fix the problem.
> fix: target should be immutable in smoothDamp

- .github/workflows/release.yml
- .releaserc.json
In order to trigger a release when pushing on `master` (rather than `dev`) as discussed in https://github.com/yomotsu/camera-controls/pull/365
---
don't miss out to:
All the rest should be good if I don't forget anything...
NB: maybe if one day, merge-queue becomes available for personal repos, we could go back to `dev` ;)
> `master` as release-branch

- examples/pointer-lock.html
- readme.md
- src/CameraControls.ts
Add simple internal compatibility with [PointerLock API](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock) / [three.js PointerLockControls](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/PointerLockControls.js).
Currently CameraControls acknowledges PointerLock API in `onPointerMove` by calculating [delta values](https://github.com/yomotsu/camera-controls/blob/dev/src/CameraControls.ts#L993) - but since controls become reactive only after at least one `onPointerDown / onMouseDown` event - PointerLock's arguably most practical use-case, a first-person camera, is not achievable (user would need to hold down a button to make controls listen to events.)
Changes:
* `pointerlockchange` and `pointerlockerror` listeners …
> Add PointerLock API compatibility

- src/CameraControls.ts
reported in https://github.com/yomotsu/camera-controls/issues/389
`updateCameraUp()` didn't work correctly because it doesn't update yAxisUpSpaceInverse due to typo.
The problem was caused by https://github.com/yomotsu/camera-controls/commit/6b8aa4f8678f7b7765bb7144705851e8924f3f6a#diff-a7487850c504598a4d5cfd4300c570c2cfeebab9cb158675a7ef8a30faac4d8cR2204
> fix: updateCameraUp doesnt update _yAxisUpSpaceInverse

- examples/basic.html
- readme.md
- src/CameraControls.ts
At present, when dollying/zooming via drag, pressing the mouse button and dragging up dollies/zooms out and dragging down dollies/zooms in.
However, this is the opposite of how 3D design software from Autodesk and others work, so the new `dollyDragInverted` property enables developers to invert this functionality, so that dragging up dollies/zooms in and down dollies/zooms out.
This update does not affect dollying/zooming via the mouse wheel.
A checkbox has been added to the basic example to demonstrate this functionality.
> Add dollyDragInverted property

- examples/basic.html
- examples/camera-up.html
- examples/pointer-lock.html
- readme.md
- src/CameraControls.ts
- `lockPointer()` and `unlockPointer()` are now public methods.
- Previously, the pointer created with PointerLock was an ordinary pointer and could be accidentally removed, but I added the `this._lockedPointer` field as an instance of the special pointer, to save from the problem.
- accept the right button dragging
https://user-images.githubusercontent.com/212837/223721937-89f6680c-4427-4fa6-a723-52b82c98d10e.mp4
> expose lockPointer and unlockPointer methods

- .github/workflows/release.yml
so there is no need to hard-code it into the workflow file: https://stackoverflow.com/a/62978089/133327
> chore(release): actions/setup-node reads .node-version file

- src/CameraControls.ts
closes #411
`if ( this.verticalDragToForward )` check was nested inside `if ( isPerspectiveCamera( this._camera ) )` and not repeated inside `else if ( isOrthographicCamera( this._camera ) )`. I am assuming this was not intentional. 
Now the code for applying `_truckInternal` is the same for both camera types, except `truckX` and `pedestalY` are resolved in different ways.
I changed camera to orthographic in some examples and it seems to work fine with `verticalDragToForward` enabled but more testing is needed I think.
> fix: verticalDragToForward has no effect when used with OrthographicCamera

- src/CameraControls.ts
related to https://github.com/yomotsu/camera-controls/issues/425
> fix: setTarget moves the camera to unexpected positions by the angle

- src/CameraControls.ts
After running `applyCameraUp`, the `_camera.up` vector gets used to create a quaternion in `updateCameraUp` via `setFromUnitVectors` - since the cross product of two vectors isn't normalized unless the two vectors are orthogonal two eachother, the resulting `_camera.up` ends up being non-normal, and causes the quaternion generation to get upset. This change just re-normalizes the output of the cross product.
> Re-normalize new camera up after cross product

- examples/await-transitions.html
- examples/fit-to-bounding-sphere.html
- examples/rest-and-sleep.html
BoxBufferGeometry -> BoxGeometry
SphereBufferGeometry -> SphereGeometry
I found this after looking at the fit-to-bounding-sphere example and got the error:
Uncaught (in promise) TypeError: THREE.SphereBufferGeometry is not a constructor
at fit-to-bounding-sphere.html:69:3
> fix: deprecated geometry from examples

- src/CameraControls.ts
The height of `_elementRect` will be used as a divisor but could be 0 until `_elementRect` is initialized.
thus _elementRect should be updated right after connecting to the dom.
> fix: prevent divide-by-zero

- src/CameraControls.ts
Reproduction/demonstration of the bug: https://jsfiddle.net/wellcaffeinated/zdb05n2u/
Correctly works when orbit target (green box) is at origin. But when moved (elevate), the look direction is improperly calculated.
This fixes the problem with the vector math.
> Bugfix for incorrect "lookInDirectionOf" behaviour when camera orbit target is not at origin

- readme.md
This markdown seems to have been written by mistake.
```diff
- An alias of 1setLookAt()1, without target change.
+ An alias of `setLookAt()`, without target change.
```
> chore: there's a typo in README

- readme.md
- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/530
> feat: add stop method

- src/CameraControls.ts
As a result of #556, there is some *wobbling* when rapidly rotating the scene (if using focalOffset). Re-adding the earlier call to `_camera.updateMatrixWorld` fixes this.
This PR directly calls `_camera.matrix.compose` rather than calling `updateMatrixWorld` to avoid unnecessary calculations.
Regards,
Harrison
> fix: Re-added _camera.updateMatrixWorld() as via _camera.matrix.compose()

- src/CameraControls.ts
This aims to fix the issues #519 #461 where using the trackpad to zoom is very slow compared to the mouse wheel.
Fixed it by checking `ctrlKey` in the event and increasing the delta. This property is set by the browser to true when using multi touch gestures on the trackpad.
Since both issues reference using an orthographic camera and I'm using one myself in my project this needs to be tested using a perspective camera as well. I will try and find time to do it
> fix: trackpad pinch to zoom speed

- examples/PseudoElement.js
Hey,
I just added the PseudoElement to the PseudoDocument constructor as requested [here](https://github.com/yomotsu/camera-controls/issues/569#issuecomment-2869865117) :) 
Hope this is useful for completing the worker example. My implementation was a bit hacky, you'll know better what to do, just as a reference, this is what I did (building on top of your worker example).
```js
// define extra pointer move event to be used when the pointer gets locked 
const onPointerMovePointerLock = (event: any) => {
if (event.cancelable) event.preventDefault();
const pseudoPointerEvent = {
pointerId: event.pointerId,
pointerType: event.pointerType,
clientX: event.clientX,
clientY: event.clientY,
movementX: event.movementX,
movementY: event.movementY,
buttons: 1, // <- this tricks camera controls into …
```
> Added PseudoElement to PseudoDocument Construcutor

- examples/basic.html
- src/CameraControls.ts
- src/types.ts
a "general" `lerp()` method, between 2 states that can:
1. either includes: `(target,position)` -- like `lerpLookAt`
2. or: `(target,spherical)` -- NEW now with support for spherical values
```tsx
// 1.
cameraControls.lerp(
{target: [1,0,0], position: [-2,0,0]}, // stateA
{target: [-1,0,0], position: [0,2,5]}, // stateB
.5,
true
)
// 2.
cameraControls.lerp(
{target: [0,0,0], spherical: [2,0,      -Math.PI/2]}, // stateA
{target: [0,0,0], spherical: [7,Math.PI, Math.PI/2]}, // stateB
//                               ^polar   ^azimuth
//                            ^radius
.5,
true
)
```
illustration of `lerp` with spherical (2.):
|aligned targets|different targets|
|-|-|
|![shapes at 25-07-10 16 42 29](https://github.com/user-attachments/assets/b632dae3-8378-4e8a-9439-a539dceaadc5)|![shapes …
> feat: `cameraControls.lerp` position or spherical
