- examples/basic.html
- src/camera-controls.js
When it's true, dolly using mouse wheel / touch makes it zoom toward its cursor position / touch position.
> dollyToCursor

- src/camera-controls.js
This PR is to support 2 finger pan (truck)
> 2 finger pan

- src/camera-controls.js
> dollyToCursor: now it can think about minDistance / maxDistance

- package.json
types folder is not under the src, perhaps you mean `types/camera-controls.d.ts`?
> modify types path

- src/camera-controls.js
> forward must have _encloseToBoundary too

- examples/viewport.html
Add an example that can be used to examine `cameraControls.setViewport()` .
> New example: viewport.html

- examples/collision.html
- readme.md
- src/camera-controls.js
the camera near plane vs colliders, as an experimental feature.
> collision test

- examples/config.html
- readme.md
- src/CameraControls.ts
- src/constants.ts
- src/types.ts
see https://github.com/yomotsu/camera-controls/pull/66#issuecomment-572880522
> add trackpad config

- src/CameraControls.ts
> remove unexpected console.error

- package-lock.json
- package.json
- src/CameraControls.ts
- src/types.ts
see https://github.com/yomotsu/camera-controls/issues/70
> downgrade to TS3.0.x

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/74
> touchmove as passive: false

- examples/config.html
- readme.md
- src/CameraControls.ts
- src/constants.ts
- src/types.ts
see https://github.com/yomotsu/camera-controls/pull/67#issuecomment-581256041
> remove trackpad config and merge it as the wheel config

- .eslintignore
- package.json
> eslint should ignore dist and node_modules

- package-lock.json
- package.json
- src/CameraControls.ts
- update ts version to 3.8.2
- downlevel d.ts version to 3.4. see https://github.com/yomotsu/camera-controls/issues/70
- use type-only option
> update ts version and downlavel d.ts version

- src/CameraControls.ts
normalizeRotations() should ignore negative value
> normalizeRotations() should ignore negative value

- src/CameraControls.ts
fixes https://github.com/yomotsu/camera-controls/issues/105
> toJSON should save movement end value

- src/CameraControls.ts
- src/types.ts
to enable event name suggestions and event interface.
> better event type interface

- readme.md
> Fidex typo in documentation

- src/CameraControls.ts
refs https://github.com/yomotsu/camera-controls/issues/124
Add a condition to detect running on whether browser or node.
> Detect whether node or browser

- examples/iframe-child.html
- examples/iframe.html
- readme.md
- src/CameraControls.ts
reported in https://github.com/yomotsu/camera-controls/issues/144
> support iframe outside dragging

- package-lock.json
- package.json
- src/CameraControls.ts
- src/utils/quatInvertCompat.ts
Will resolve #151 
- Three.js is now r123
- `Quaternion.inverse` -> `Quaternion.invert`
- Compat is implemented for backward compatibility
> Bump three r123

- examples/basic.html
- examples/orthographic.html
fixes https://github.com/yomotsu/camera-controls/issues/153
> fitTo should be fitToBox

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/162
> fix issue 162

- package-lock.json
- package.json
Addresses #171 .
Change dev dependency requirements for 
- @types/three
- three
and peerDependencies peerDependencies for 
- three
from "^0.126.1" to ">=0.126.1", to accept upcoming versions of three.js .
> Relax three.js dependencies

- examples/basic.html
- src/CameraControls.ts
Fixes > [Issue 175](https://github.com/yomotsu/camera-controls/issues/175)
> added support for infinity dolly while using dolly to cursor

- src/CameraControls.ts
- src/types.ts
- src/utils/extractClientCoordFromEvent.ts
- src/utils/isTouchEvent.ts
This PR is to support PointerEvents for user gestures.
But also keep mouse and touch events for Safari 12. (will be removed someday though)
> add PointerEvents supports

- readme.md
- src/CameraControls.ts
This PR is adding getter / setter for the camera, based on https://github.com/yomotsu/camera-controls/pull/195
> feat: Add a Getter and Setter for the camera (cleanedup)

- examples/first-person.html
- src/CameraControls.ts
InfinityDolly and dollyToCursor now work with `mouseButtons.wheel = CameraControls.ACTION.DOLLY` in first person.
I think there are ways to improve because if i set
`cameraControls.minDistance = cameraControls.maxDistance = EPS;`
Mouse wheel do nothing.
You can try first person infinity dolly to cursor here : https://first-person-infinity-dolly-to-cursor.netlify.app/
> Feat: Allow first person dolly

- src/utils/notSupportedInOrthographicCamera.ts
Trying to build from master it is crashing due to this `types` import not found.
> Fix invalid import

- readme.md
- src/CameraControls.ts
- src/utils/math-utils.ts
see https://github.com/yomotsu/camera-controls/issues/214
If the final point of camera moving methods is already set, the Promise is not returned. this RR is to fix the problem.
> return missing promise

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/255
> fix: setLookAt with transition enabled never resolves with off-center target 

- src/EventDispatcher.ts
see https://github.com/yomotsu/camera-controls/issues/264
> dispatchEvent should be public

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/276#issuecomment-1169418981
> fix fitToBox with padding in none-y-up space

- src/CameraControls.ts
- src/types.ts
see https://github.com/yomotsu/camera-controls/issues/282
This PR is to support pointer lock API.
> support PointerLock API

- readme.md
- src/CameraControls.ts
- src/types.ts
see https://github.com/yomotsu/camera-controls/issues/282
This PR is to allow multi-button press dragging in the mouse device.
> support multi-button mouse drag

- readme.md
- src/CameraControls.ts
- src/types.ts
see https://github.com/yomotsu/camera-controls/issues/285
> Fix mouse middle button

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/290
> fix: CurrentAction always returns 0

- src/CameraControls.ts
this PR is to fix
- https://github.com/yomotsu/camera-controls/issues/310
> fix focalOffset related problems

- examples/event-attach.html
- readme.md
- src/CameraControls.ts
- prevent double connecting
- add 'disconnect()' method to disable dragging
- add docs for `connect()` and `disconnect()`
> Organize event hander attaching

- readme.md
- src/CameraControls.ts
- src/types.ts
- src/utils/math-utils.ts
TBW
see https://github.com/yomotsu/camera-controls/issues/340
> use smoothDamp instead of three.js's damp

- readme.md
could be useful for those coming from `camera-controls` and looking for r3f "official" example ;)
> updating r3f example

- src/CameraControls.ts
wheel zoom has been broken after v2.
this PR is to fix the problem.
> fix wheel zoom

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/354
> avoid divide-by-zero

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/361
> Enable contextmenu

- readme.md
- src/CameraControls.ts
see: https://github.com/yomotsu/camera-controls/issues/367
TBW
> feat: add elevate method

- examples/auto-rotate.html
- examples/await-transitions.html
- examples/basic.html
- examples/boundary.html
- examples/camera-up.html
- examples/click-to-set-orbit-point.html
- examples/collision.html
- examples/combined-gestures.html
- examples/config.html
- examples/cursor.html
- examples/easing.html
- examples/effect-shake.html
- examples/event-attach.html
- examples/first-person.html
- examples/fit-and-padding.html
- examples/fit-to-bounding-sphere.html
- examples/focal-offset.html
- examples/iframe-child.html
- examples/keyboard.html
- examples/look-in-direction.html
- examples/mouse-drag-with-modifier-keys.html
- examples/orthographic.html
- examples/padding-with-view-offset.html
- examples/path-animation.html
- examples/rest-and-sleep.html
- examples/viewport.html
a single `<script type="module">import ...` for `examples/*`
> esm examples scripts

- src/CameraControls.ts
reported: https://github.com/yomotsu/camera-controls/issues/396
this PS is to fix the problem
> fix: fromJSON does not apply dolly distance

- src/CameraControls.ts
This PR is to fix https://github.com/yomotsu/camera-controls/issues/417
> fix: dollyToCursor with smooth

- readme.md
- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/426
> add getSpherical and allows receiveEndValue for other get** methods

- examples/basic.html
- examples/infinity-dolly.html
- readme.md
- src/CameraControls.ts
- src/types.ts
see https://github.com/yomotsu/camera-controls/issues/425
re-enable ranged distance infinityDolly.
If users use `infinityDolly`, the user must set min/maxDitance too.
https://github.com/yomotsu/camera-controls/assets/212837/58aa737c-d24a-4d4b-aed6-c1872cb51b82
> feat: ranged infinityDolly

- src/CameraControls.ts
This PR is to fix https://github.com/yomotsu/camera-controls/issues/464
> fix: setting interactiveArea top position

- package.json
ref: https://github.com/yomotsu/camera-controls/issues/481
This PR should solve the above problem.
> fix: package.json exposed a wrong js file

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/510
> fix: avoid using instanceof for three object

- src/CameraControls.ts
see https://github.com/yomotsu/camera-controls/issues/515
> fix: issue 515

- readme.md
drei doc has change, let's just update it :)
> docs: updating drei url
